#!/bin/bash

# Display available updates for JBang aliases

set -eu -o pipefail
shopt -s extglob

readonly VERSIONS_PLUGIN=org.codehaus.mojo:versions-maven-plugin:2.16.2
readonly BOLD='\033[1m'
readonly YELLOW='\033[33m'
readonly NOCOLOR='\033[0m'

display_dependency_updates_for_one_pom() {
  pom_file=$1

  # Extract the alias name from the pom file path
  : "${pom_file/#pom_files\/}" # trim leading 'pom_files/`
  alias_name="${_/%\/pom.xml/}"  # trim trailing '/pom.xml

  echo -e "- $BOLD$YELLOW$alias_name$NOCOLOR:"
  updates=$(
    mvn -f "$pom_file" "$VERSIONS_PLUGIN":display-dependency-updates \
      | awk '/The following dependencies/{flag=1; next}
             /^\[INFO\] *?$/{flag=0}
             $1=""
             flag {print "", $0}'
  )
  echo "${updates:-  (No dependency updates available)}"
}

echo "Available updates:"
pom_files=(pom_files/*/pom.xml)
if [[ ${#pom_files[@]} -eq 0 ]]; then
  echo "No pom files found. Did you run `generate_pom_files`?"
else
  for pom_file in "${pom_files[@]}"; do
    display_dependency_updates_for_one_pom "$pom_file"
  done
fi

